[package]
name = "axum-otel-metrics"
version = "0.9.0-alpha.2"
edition = "2021"
license = "MIT"
description = "axum OpenTelemetry metrics middleware with prometheus exporter"
homepage = "https://ttys3.dev/"
repository = "https://github.com/ttys3/axum-otel-metrics/"
documentation = "https://docs.rs/axum-otel-metrics"
readme = "README.md"
exclude = [".github/*", "examples/*", "tests/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum = "0.7.5"
opentelemetry = { version = "0.24", features = ["metrics"] }
opentelemetry-semantic-conventions = { version = "0.16.0"}

tower = "0.4.13"
futures-util = "0.3.30"
pin-project-lite = "0.2.14"
#http = "1.1.0"
http-body = "1.0.1"
#opentelemetry-otlp = { version = "0.17.0", features = ["metrics", "http-proto", "reqwest-client"] }
#opentelemetry-http = "0.13.0"


[dev-dependencies]
tokio = { version = "1.39.2", features = ["macros"] }
opentelemetry_sdk = { version = "0.24.1", features = ["rt-tokio"] }